### ISSUE TITLE
Not an issue but pickable pets would be a neat mod and may reuse functions of this mod

### ISSUE THREAD

**Issue by ImpulsiveLad** [shiftthedev/PickablePets#1]
I'm looking at this mod and wondering how it works, picking up villagers is helpful but man I wish I could pick up pets, I always tame a cat thousands of blocks from my base and I gotta use a waystone or something since walking that is going to take ages. I know this mod is pickable villagers but I'm wondering how different a mod would need to be to pick up other mobs

**Comment by shiftthedev** [comment]
The problem isn't creating new itens for every pet, but how the entity is created.
I can get all entities that implement the Tameable interface to work, but if a modded pet doesn't make use of it, it won't function.

Nevertheless, it's still a great idea.

**Comment by shiftthedev** [comment]
Some initial testing. It works!! Still need to do some more testing, like server-client and modding mobs.
https://github.com/shiftthedev/PickablePets/assets/29488158/5fbe9a84-5836-48b9-8958-fa750d2510b8

**Comment by ImpulsiveLad** [comment]
Awesome, hope it works out without issue.

**Comment by ImpulsiveLad** [comment]
Not sure if you got to do anymore work on the mod but I'll gladly test how it works out with modded entities, afaik if jade shows them as tamed and having an owner then this mod *should* work for them

**Comment by shiftthedev** [comment]
there will be a version available today

**Comment by shiftthedev** [comment]
It's available at [Modrinth](https://modrinth.com/mod/pickable-pets), and waiting approval at [Curse](https://legacy.curseforge.com/minecraft/mc-mods/pickable-pets).

**Comment by shiftthedev** [comment]
1.19 and 1.20 version are currently under review. Don't know how long will it take.
[Modrinth](https://modrinth.com/mod/pickable-pets)
[Curse](https://legacy.curseforge.com/minecraft/mc-mods/pickable-pets)

**Comment by ImpulsiveLad** [comment]
Not related but is pickable villagers only on fabric? I searched for the forge version and couldn't find it

**Comment by shiftthedev** [comment]
> Not related but is pickable villagers only on fabric? I searched for the forge version and couldn't find it

I made Pickable Villagers because Easy Villagers didn't had a Fabric version. 
So to avoid problems I didn't launch it on Forge.

**Comment by ImpulsiveLad** [comment]
Ah I see, didn't know that existed
