### ISSUE TITLE
Game/Server Crash on Starting With Pickable Pets Installed

### ISSUE THREAD

**Issue by MomoTheKemono** [shiftthedev/PickablePets#10]
When attempting to load the game or server with pickable pets both will crash. This is a mod I'm really hoping to get to work (and also hoping it works with pets added by other mods, because we're trying to find a way to take larger mounts with us places). This is the only mod I've found that does this for 1.20.1.  I'm not sure if anyone else has encountered this issue, but if there's something I can do to correct it, please let me know. 

I have provided my crash report and latest.log. I don't see any notes of incompatibilities yet on the mod site. When I have time I can try to remove mods one at a time to see if there's a specific conflict.

[latest.log](https://github.com/shiftthedev/PickablePets/files/13846270/latest.log)
[crash-2024-01-05_15.16.09-fml.txt](https://github.com/shiftthedev/PickablePets/files/13846212/crash-2024-01-05_15.16.09-fml.txt)

**Comment by shiftthedev** [comment]
you're missing [Cloth Config](https://legacy.curseforge.com/minecraft/mc-mods/cloth-config)

**Comment by MomoTheKemono** [comment]
Awesome I'll give that a try!
