### ISSUE TITLE
Fabric 1.20.1 Pet stats are changed after pickup.

### ISSUE THREAD

**Issue by Sephoix** [shiftthedev/PickablePets#11]
Minecraft version: 1.20.1
Modloader: Fabric Version 0.15.3
Mod version: 1.2.1

Playing on version 1.2.1 and I happened to notice a odd little bug that affects horses and other animals with health, jump, and speed stats and values. Original stats get overridden and changed once I pick up the pet for the first time and set them down.

 Before:
![2024-01-16_15 28 38](https://github.com/shiftthedev/PickablePets/assets/85546419/96bf2a6f-e3fa-4b3f-978f-15437691c5fc)

After: 
![2024-01-16_15 28 52](https://github.com/shiftthedev/PickablePets/assets/85546419/2e26c834-37a9-4382-acdb-f4e1b5685b01)

I even went as far as to only running this mod by itself (with the exception of wthit) and the bug still is present for animals.

Horses before being picked up:
![2024-01-16_15 36 11](https://github.com/shiftthedev/PickablePets/assets/85546419/3abbab3c-192c-43ba-a6ae-381565931bd8)
![2024-01-16_15 37 11](https://github.com/shiftthedev/PickablePets/assets/85546419/bb1b0982-fee0-4eb2-af85-d866037c7cd2)

Horses after being picked up and set back down:
![2024-01-16_15 36 24](https://github.com/shiftthedev/PickablePets/assets/85546419/3c69b2dd-7d0a-47dc-bbbc-82bc039a9475)
![2024-01-16_15 37 16](https://github.com/shiftthedev/PickablePets/assets/85546419/8cd1659e-65ca-42f5-806d-9edb592afc3b)

Here is the log I had during testing.
https://mclo.gs/szxxfmQ

**Comment by shiftthedev** [comment]
this shouldn't be happening. thanks for reporting I'll look into it as soon as I can.

**Comment by VeggeieDude** [comment]
Oooh, I was wondering why my horse had 53 hp out of nowhere XD

**Comment by shiftthedev** [comment]
Fixed in 1.2.2
