### ISSUE TITLE
Picking up pets causes bugs

### ISSUE THREAD

**Issue by SireAwfulThe1st** [shiftthedev/PickablePets#12]
having a really annoying problem where if you started picking a pet, you suddenly cant use any type of tools/items because it weirdly doesn't detect _anything_ in your hand or Inventorio's toolbar.

https://github.com/shiftthedev/PickablePets/assets/106896635/8937adb0-9736-450e-bd3b-d30064eed3af

hope this video makes it more understandable incase my description is a bit awkward tae understand. Cheers

**Comment by shiftthedev** [comment]
you tried to pick a pet and it failed for so reason and now you're bugged? you picked a pet and place down and now you're bugged?? 
sorry but I couldn't understand neither the description nor the video.
if possible add a log after this happen.
