### ISSUE TITLE
1.20.1 Forge Pets having their stats overwritten

### ISSUE THREAD

**Issue by JustNachi** [shiftthedev/PickablePets#13]
I am having the same issue as Sephoix, but with Forge. I didn't do extensive testing, but I did notice a difference in my second horse's stats after picking it up. I was excited and chose it because it had 12 speed or something and over 3 jump. However, after I picked the horse up, it was noticeably slower. When I looked at it again, I noticed it had downgraded to 9.48 speed and 2.89 jump. I happened to look at my other horse and noticed the stats were the same as it, with the exception of the second horse having 69 health and the new horse having 64.

Minecraft version: 1.20.1
Modloader: Fabric Version 47.2.20
Mod version: 1.2.1
[latest.log](https://github.com/shiftthedev/PickablePets/files/14733939/latest.log)

**Comment by shiftthedev** [comment]
Fixed in 1.2.2
