### ISSUE TITLE
Unable to revive pets

### ISSUE THREAD

**Issue by Riyuukii** [shiftthedev/PickablePets#14]
Hello! for some reason I can't manage to get the revive altar working with forge 1.18.2, my wolf died but the wolf on the altar doesnt seems to be "died", and right clicking with diamond doesnt do anything. Am I doing something wrong? Any help would be appreciated ^^

(Also, english is not my native language, so I apologize for my improper grammar.)
![image](https://github.com/shiftthedev/PickablePets/assets/74540871/352cf484-b785-4df7-a240-4ec0a85881dc)
![image](https://github.com/shiftthedev/PickablePets/assets/74540871/3280dd8d-5636-4499-b255-0cb16040cf11)

**Comment by shiftthedev** [comment]
I'm unable to replicate this.
what version of the mod? 
try reviving and then go to https://mclo.gs and share the latest.log file so I can check for errors.

**Comment by Riyuukii** [comment]
Pickable Pets 1.2.2 for 1.18.2 forge, installed on the latest dawncraft version.
logs file (latest): https://mclo.gs/sOCNzVn

**Comment by shiftthedev** [comment]
After some investigation there seems to be an incompatibility with one or more mods in that pack.
As soon as I have some free time I will try to find the source of the problem and try to fix it.

Thanks for reporting.

**Comment by shiftthedev** [comment]
Fixed in 1.2.3.
Also added /petrevive [POS] command to allow OPs in creative to revive pets in altars.

**Comment by Riyuukii** [comment]
You've done a really good job! Would you mind telling me which mod(s) that caused the problem by any chance? ^^

**Comment by shiftthedev** [comment]
[Saturn Mod](https://www.curseforge.com/minecraft/mc-mods/saturn) was the problem.
