### ISSUE TITLE
Pet item does not always match the mob texture when picked up if multiple textures are available for the mob

### ISSUE THREAD

**Issue by trashraccoon42** [shiftthedev/PickablePets#15]
For mobs that have variants (eg. Shibas in quark, or wolves when using a texture pack which adds variants) it does not always seem to display the original pet in the item, sometimes it has other textures. This does not happen with minecraft cats.

https://github.com/shiftthedev/PickablePets/assets/73861642/4eaa4783-af24-4b16-984d-191d05ef3c19

**Comment by shiftthedev** [comment]
this is funny but shouldn't be happening. I'll look into it.
