### ISSUE TITLE
[Suggestion] Pet Respawn

### ISSUE THREAD

**Issue by ImpulsiveLad** [shiftthedev/PickablePets#2]
There is really only one modern pet respawn mod and its fabric exclusive. I have good ideas for how this mod can have a mechanic such as that but possibly better, it would make sense to be part of this mod to me, but it should always be able to be turned off entirely in config:

My idea is that there is a craftable item (maybe ender pearl, 2 gold bars, 2 amethyst shard) and it can be used by first left clicking the tamed mob, then shift left clicking an open space (Afterwards the item is used up and the tile becomes an invisible respawn block. (emits ender particles when the mob is dead)

I would personally say it would be best if the respawn is on command and requires you to interact with the respawn point to spend X xp levels and bring them back. It can be configurable how many times they can be respawned on the point before it expires and you have to make another respawn before they die again (or it can be set to infinite respawns.)

I know this would be a very large feature but what do you think?

**Comment by shiftthedev** [comment]
OMG!! A Respawn Anchor for pets!! 
I'll put it on my list, but I can only work on the mod on the weekends.

**Comment by ImpulsiveLad** [comment]
Awesome, I’m excited to see how it works out, if you want input on something then I’ll be here to give mine :)

**Comment by shiftthedev** [comment]
![java_LU9tr6xDKS](https://github.com/shiftthedev/PickablePets/assets/29488158/6ddbbd0e-956d-4625-97b1-75c5d767e7ed)
Respawn Altar for dead pets.

**Comment by ImpulsiveLad** [comment]
That looks pretty good

**Comment by shiftthedev** [comment]
a quick update on this, i'm still working on it but minecraft is being minecraft and it's messing with the way i'm checking if the pet is dead. 
need to look into a different approach to this.

**Comment by shiftthedev** [comment]
![altar_preview](https://github.com/shiftthedev/PickablePets/assets/29488158/c7785fd8-ce30-4324-a732-6dbd4feb3d99)

it's working! missing some better positioning.

**Comment by ImpulsiveLass** [comment]
cool cool cool

**Comment by shiftthedev** [comment]
just a quick update! 
if everything goes right, this will be out tomorrow or Monday.

**Comment by shiftthedev** [comment]
Added in 1.2.0

**Comment by CherubicBoot** [comment]
Hello! for some reason I can't manage to get the revive altar working with forge 1.18.2, my wolf died but the wolf on the altar doesnt seems to be "died", and right clicking with diamond doesnt do anything. Am I doing something wrong? Any help would be appreciated ^^

(Also, english is not my native language, so I apologize for my improper grammar.)
![image](https://github.com/shiftthedev/PickablePets/assets/74540871/352cf484-b785-4df7-a240-4ec0a85881dc)
![image](https://github.com/shiftthedev/PickablePets/assets/74540871/3280dd8d-5636-4499-b255-0cb16040cf11)
