### ISSUE TITLE
internal exception:java.util.ConcurrentModificationException:Async Entity Unload error occurs minecraft after I try to use this mod and crashes the game. I don't know why

### ISSUE THREAD

**Issue by Sayam-Ganguly** [shiftthedev/PickablePets#21]
For reference I am using Minecraft Java 1.20.1 Fabric and I am using a lot of mods as well. But everything works perfectly until I use PickablePets. Then the game just crashes and shows this error "internal exception:java.util.ConcurrentModificationException:Async Entity Unload" then I have to restart the world again. The functionality works tho as the pet comes into my inventory.

It happens every time I use this mod, I press the selected keybind for the mod, the game crashes, I restart the world and the pet is in my inventory.

**Comment by shiftthedev** [comment]
Without a stack trace that is in a crash-report, it's impossible to know what is happening because I'm unable to replicate this issue.

**Comment by Sayam-Ganguly** [comment]
Yeah I am on it, please wait.

**Comment by Sayam-Ganguly** [comment]
I am relatively new in MInecraft, I don't know where to get the stack trace from so I just copied the entire logger information here and uploaded the text file, hope it helps otherwise I don't know...
[Logger Info.txt](https://github.com/user-attachments/files/16839079/Logger.Info.txt)

**Comment by shiftthedev** [comment]
yes this helps

**Comment by Sayam-Ganguly** [comment]
I can upload my mod folder here if you need it and thanks for replying : )

**Comment by shiftthedev** [comment]
no need, the log already has the list of mods

**Comment by Sayam-Ganguly** [comment]
okay

**Comment by shiftthedev** [comment]
quick question, is this happening when using the keybing and the sneak+right-click?

**Comment by Sayam-Ganguly** [comment]
I am not using the sneak+right click beacuse it is binded to carryon mod which allows you to pick up anything, but I key binded it to pickable pets to key Y, and yes the game crashes after I use my selected keybind.

Have a good day :)

**Comment by Sayam-Ganguly** [comment]
so uh any news ?

**Comment by shiftthedev** [comment]
the culprit for the crash is [Concurrent Chunk Management Engine (Fabric)](https://www.curseforge.com/minecraft/mc-mods/c2me-fabric)
I don't know why it happens and, because that mod is in alpha, making a compatibility to it is not viable.
I've tested sneak+right click and it doesn't crash, what makes this even more confusing.

**Comment by Sayam-Ganguly** [comment]
so ihave to remove concurrent chunk management for the crash to not occur?

**Comment by shiftthedev** [comment]
yes, removing that mod stops the crashing.

**Comment by Sayam-Ganguly** [comment]
Hello my apologies for confirming your findings so late, yes Concurrent Chunk Management was the culprit, that mod is still in alpha and is meant for server side only I just downloaded that without looking into it much. I can pick up my wolves without crashing the game now, thanks.

Have a good day.
