### ISSUE TITLE
Revive altar still giving a paper for pets you didn't pick

### ISSUE THREAD

**Issue by GoldenFurredFox** [shiftthedev/PickablePets#23]
Revive altar gives a paper for any tamed animal, regardless of picking. I had a camel die of fall damage without ever having picked them, and still got a paper, but the paper it gave cannot be used on the altar.

[GIF of the issue](https://i.postimg.cc/7Zdnx3W7/javaw-a-H2-VZIHgw-M.gif)

**Comment by shiftthedev** [comment]
- Revive Altar functions as a save for your pets.
   - Right click with a pet in item form to save it in the altar.
   - If the pet dies, right click the altar with the revive item to revive it. (default: Diamond)
   
Paper drops has nothing to do with this mod.
If you didn't setup the altar with the pet, you won't be able to revive it.

**Comment by GoldenFurredFox** [comment]
I have no idea what mod the paper comes from, then. That's confusing. Regardless, thank you for the help.
