### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by ImpulsiveLad** [shiftthedev/PickablePets#4]
I have no recorded anything yet, its 2:36am but I was wanted to make note before I forget that certain nonsolid blocks become de-rendered when you have a mob in your inventory, I noticed this with some plant decorations and beds. I was carrying a ray cat the bed time and a subterranadon the plant time.

**Comment by shiftthedev** [comment]
When you can please provide a short video and the lastest.log

**Comment by ImpulsiveLad** [comment]
https://streamable.com/4g7488
not sure if this is what latest log is but 
[2023-11-01-1.log.gz](https://github.com/shiftthedev/PickablePets/files/13232937/2023-11-01-1.log.gz)

**Comment by ImpulsiveLad** [comment]
Can confirm the lag spikes vanished completely when I updated to 1.1.0, the assets becoming derendered still occurs

**Comment by shiftthedev** [comment]
Fixed in 1.2.0
