### ISSUE TITLE
Cannot Pickup Horses

### ISSUE THREAD

**Issue by Nyoodle** [shiftthedev/PickablePets#5]
(sorry if I'm doing this wrong, my first time ever making an issue on here I had to make an account)

So here is the log 
[2023-11-09-6.log.gz](https://github.com/shiftthedev/PickablePets/files/13322063/2023-11-09-6.log.gz)

I do have other mods, but the only horse related ones are the horse genetics mod and horse stonks mod (please let me know if you need anything else as I'm not sure)

**Comment by shiftthedev** [comment]
this is fine.
i'll look into it and try to find the problem.

**Comment by shiftthedev** [comment]
this will be fixed in the next update.

**Comment by shiftthedev** [comment]
Fixed in 1.2.0
