### ISSUE TITLE
New update breaks old pets.

### ISSUE THREAD

**Issue by Sephoix** [shiftthedev/PickablePets#6]
After updating to 1,2 from version 1.1 all the previous pets I had in either my inventory or chest was not rendered. The item data was still there and I could still pick up and move the pets around, but trying to place/spawn them did nothing. Reverting back to version 1.1 was able to restore full access and rendering of the pets.

**Comment by shiftthedev** [comment]
minecraft version?
any other mods?
if you can provide a log

**Comment by Sephoix** [comment]
Minecraft version 1.20.1 with Fabric.
I do have other mods but there was no conflicts or issues as I've narrowed it specifically the update from 1.1 to 1.2.
Here are a couple images to show the results and this affected both pets in my inventory and chests.

![image](https://github.com/shiftthedev/PickablePets/assets/85546419/32c33e63-9e62-47ff-ad30-f9fb8569b55b)
![image](https://github.com/shiftthedev/PickablePets/assets/85546419/7731f65d-9086-46a3-bac0-33bbaa1e0c9c)

Nothing shows up in the logs even when I attempt to place down the pets in this bugged state. Though on a side note the game does crash when using the container search mod with 1.2 update.
![image](https://github.com/shiftthedev/PickablePets/assets/85546419/63cc3f48-6b0e-4442-8c56-25d51ca4d6c4)

Thankfully I can just revert back to version 1.1 for the time being.

**Comment by shiftthedev** [comment]
this is probably a mod incompatibility that I didn't found.
I'm in a process to fix a client-server bug that will probability fix this too.

**Comment by Sephoix** [comment]
Alright, I'll keep an eye out for the time being. And if it should help I shall provide a full log of my instance with version 1.2.

https://mclo.gs/nEIosUT

**Comment by shiftthedev** [comment]
try version [1.2.1](https://legacy.curseforge.com/minecraft/mc-mods/pickable-pets) and if possible let me know if this is still happening

**Comment by Sephoix** [comment]
It works now without any issue! All the pet items render just fine and I was able to place them down and the like.
