### ISSUE TITLE
1.2.0+1.20 incorrectly labeled as compatible with 1.20.1+ on Modrinth

### ISSUE THREAD

**Issue by LordOfTheWeebs** [shiftthedev/PickablePets#7]
I saw that PickablePets was labeled as available for 1.20.4 with the latest version 1.2.0+1.20, so I went to download and use it. However, after testing, it displays as incompatible for all versions above 1.20. This should be changed to show compatibility with only 1.20 to avoid confusion.

**Comment by shiftthedev** [comment]
thanks for the heads up.
fixed
