### ISSUE TITLE
Causing crash when using REI

### ISSUE THREAD

**Issue by VeggeieDude** [shiftthedev/PickablePets#9]
Heya! Super cool mod, but I ran into an issue. When using REI (roughly enough items), the game will crash if things from Pickable Pets appear. The logs say it's because the items from Pickable Pets are causing a rendering crash, specifically PetItemRenderer.

I am on Fabric version 1.20.1 and using Pickable Pets 1.2.0

Here are the logs: 
[crash-2023-12-30_03.15.24-client.txt](https://github.com/shiftthedev/PickablePets/files/13797513/crash-2023-12-30_03.15.24-client.txt)

**Comment by shiftthedev** [comment]
I'll look into it

**Comment by shiftthedev** [comment]
try version [1.2.1](https://legacy.curseforge.com/minecraft/mc-mods/pickable-pets) and if possible let me know if this is still happening

**Comment by VeggeieDude** [comment]
It works good now, ty for the fix!
